### ISSUE TITLE
hardware bug

### ISSUE THREAD

**Issue by aburrell** [SuperDARN/pydarn#59]
When preparing to test PR #52 I encountered an unrelated error `HardwareFileNotFoundError`.  This also happens on the develop branch, so I believe is related to recent changes there..  The error message doesn't help me fix it: "Hardware file for dcn radar was not found. Please insure the abbreviation is correct and there exists a hardware file for it by checking: https://github.com/vtsuperdarn/hdw.dat".  

I have the latest version of RST running and have a dcn hardware file.

Suggested changes:
- Change error message to point the user to where pydarn is accessing the hardware files locally.
- Not stop the install if hardware files are missing.  There's still things you can do without them, like load fit- and rawACF files.  Instead, indicate that functionality will be extremely limited.

**Comment by mts299** [comment]
Actually this issue was fixed with PR #45 hmmmmm 

In the setup.py file do you see this line: `check_call(['git', 'submodule', 'update', '--recursive', '--        remote'])`

Also, you may need to `git fetch` or uninstall and reinstall pyDARN depending on how you are installing it.

**Comment by mts299** [comment]
@aburrell pyDARN is not linked to RST, pyDARN gets it hardware files from the VT repo ... The error is indicating that when the git submodule updates its not grabbing the newest master commit. Thus the extra line I had to add in the setup.py 

> Change error message to point the user to where pydarn is accessing the hardware files locally.

The error is actually reporting the missing files which mean something is up on the new install... again pyDARN != DaVitpy 

> Not stop the install if hardware files are missing. There's still things you can do without them, like load fit- and rawACF files. Instead, indicate that functionality will be extremely limited.

I can add a warning but this is highly needed for Fan plots and other plotting methods as well a lot of users like myself use it for automating summary plots. So having this not load incorrectly is like saying matplotlib is not important either.

**Comment by carleyjmartin** [comment]
@aburrell , I'm just trying to recreate the bug. 
Just to clarify, theres no issue when installing, this is just when you run Dans test code for fan plots? (i.e. the install isn't being stopped by the hdw file missing?)

**Comment by mts299** [comment]
I got on the use of the code as well. Will look into this bug for now.

**Comment by aburrell** [comment]
I wasn't notified of your original comments @mts299, but was for yours @carleyjmartin!  This is happening on all branches for me.

> In the setup.py file do you see this line: check_call(['git', 'submodule', 'update', '--recursive', '-- remote'])

Yes, I see this line.  I have the code installed using develop, so I can mess with things interactively and try out new branches without needing to reinstall all the time.  

> I can add a warning but this is highly needed for Fan plots and other plotting methods as well a lot of users like myself use it for automating summary plots. So having this not load incorrectly is like saying matplotlib is not important either.

This won't be an issue with the extraction of pyDARNio, but I agree it should be kept as is here.

> The error is indicating that when the git submodule updates its not grabbing the newest master commit.

That wasn't clear for me when reading the error message.  Having tried to decode it now at various stages of understanding what the code is trying to do, I think that the message as currently written is only helpful for a higher level developer and not a user encountering it on import.  May be worth thinking about.

If I follow the instructions of the error message, I go and see that Dome C North is a radar, the code `dcn` is correct, and the git repository is fine.  The, I have no idea what's really wrong or what to do next.

I tried reinstalling, making sure my branch was up-to-date, uninstalling and reinstalling a few more times without success.

**Comment by carleyjmartin** [comment]
I think the issue is that upon install, the dcn hardware file isn't being downloaded. Leading to the error later when you try to do something like fan plots that requires all the hardware files. 
I guess the error message shouldn't really come up for 'casual pydarn users'  if the install is done correctly.  Unless there is a way to say 'if you're missing this hardware file, download it from here and stick it in this dir'? 

The same issue with the jme radar file that was fixed in #45 ?

@aburrell  are you encountering the HardwareFileNotFoundError error on import? This is an error I can't recreate.

**Comment by mts299** [comment]
The problem actually resides how you install pydarn:
If you use pip:
```
pip3 install git+https://github.com/superdarn/pydarn@develop
```
It will use the master setup.py file and not the develop one so you get the missing `dcn` file as it is missing from the hdw folder that the python exception specifies. 
 
In my case it was here:
```
ls /home/marina/hdw_bug/lib/python3.6/site-packages/pydarn-1.0.0-py3.6.egg/pydarn/utils/hdw/
```

Since the bug was fixed after master I tried the other method:
```
git clone https://github.com/superdarn/pydarn
cd pydarn
git checkout develop
pip3 install . 
```
Now it doesn't install any hardware files ... super weird 

Next I tried 
```
python3 setup.py install
```
and it worked! 

So solution is:
- [ ] How to test PR's and make note of this behavior

**Comment by mts299** [comment]
@aburrell if you are still having issue please state the steps you are doing to install, the OS, and the python version. Is it in a virtual environment? I need details. Thank you! Also, indicate where the error is appearing, during install or usage of pyDARN.

**Comment by aburrell** [comment]
I am still having issues.  I am running:

OS X Mojave
Python 3.7.7
command: python3 setup.py develop --user

Due to your prior comment I found where the hardware files are stored: `$GITDIR/pydarn/pydarn/utils/hdw/` and the `dcn` file is missing.  If I copy the missing file over from RST, pydarn loads fine.

Having thought about things a bit more I really do think that pydarn should load if some/all of the hardware files are missing.  And that the resulting warning/error message should give the user a pydarn way of updating the directory that doesn't involve reinstalling pydarn.  Perhaps this is something we could discuss at the next meeting.

**Comment by mts299** [comment]
@aburrell 
Sorry, but can you give us all the details regarding how you are installing include git commands and which branch you are on. 

then try `python3 setup.py install --user` not develop

**Comment by carleyjmartin** [comment]
I'm not sure what you mean by 'pydarn loads/pydarn should load', do you mean the plotting function you're trying to make plot something should still work if it's not specifically using that hardware file?

**Comment by aburrell** [comment]
@carleyjmartin what I mean is that pydarn should import without erroring, but let the user know which hardware file(s) are missing, and how to fix this.  However, if I had this error and only wanted to make an RTI plot (or even a fan plot!) at HAN, I would be able to make the plot I need and fix things later.  If there's an issue with one radar hardware file that takes some time to resolve, it seems like pydarn shouldn't quit working.

@mts299 the git commands I use are branch changes.  Looking at the setup.py more closely, it seems like the hardware file retrieval isn't performed when any setup command other than `install` is used.  So I suppose this is less of a bug than a 'feature'.  I am also curious how someone who doesn't install pydarn every time they use it will be able to update their hardware files.

**Comment by mts299** [comment]
Thanks, @aburrell for the feedback I think this issue has breached multiple scope and questions, so let me break it down:

1. Once this is released into master, the `pip` issue will go away because now it has the right command in place, so the actual "bug" of not getting pyDARN to work because of missing `dcn` fille will disappear. 

2. import pydarn erroring

The reason all hardware files are loaded in are for these reasons:
- There is a dictionary in SuperDARNRadars that maps all `stid` to the hardware file
Because you load in all the hardware files on import, this allows quicker and resource efficiency for grabbing radar information. 
- I use this feature a lot, and so do others when mass generating radars
- what happens if we make, so it only loads the radar you need? Well, if you are me and bouncing between radars in a mass generation, you will need to re-read all the hardware files. I work on a specific supercomputer that requires time efficiency and memory efficiency. This change will kill it. 

Since I fixed the git command in the setup.py, this should not be an issue going forward, and people will not notice. This error was more for grabbing a radar file and miss typing the acronym. 

3.  Should it error? Well, it would be nice its like matplotlib not being correctly installed. I can add, please submit an issue on github if this happens on install. 

4. Can you specify more in the exception? 
No, I cannot say where the files are because you install pyDARN in multiple places and depends on what you use. The best is to be a python person and read the traceback. 
```
Traceback (most recent call last):
  File "test_acy.py", line 1, in <module>
    import pydarn
  File "/home/marina/hdw_bug/lib/python3.6/site-packages/pydarn/__init__.py", line 36, in <module>
    from .utils.superdarn_radars import SuperDARNRadars
  File "/home/marina/hdw_bug/lib/python3.6/site-packages/pydarn/utils/superdarn_radars.py", line 271, in <module>
    class SuperDARNRadars():
  File "/home/marina/hdw_bug/lib/python3.6/site-packages/pydarn/utils/superdarn_radars.py", line 351, in SuperDARNRadars
    Hemisphere.South, read_hdw_file('dcn')),
  File "/home/marina/hdw_bug/lib/python3.6/site-packages/pydarn/utils/superdarn_radars.py", line 124, in read_hdw_file
    raise radar_exceptions.HardwareFileNotFoundError(abbrv)
pydarn.exceptions.radar_exceptions.HardwareFileNotFoundError: Hardware file for dcn radar was not found. Please insure the abbreviation is correct and there exists a hardware file for it by checking: https://github.com/vtsuperdarn/hdw.dat
```
From the traceback here is where I get my information not as a low-level developer but actually as someone who doesn't know:

location: "/home/marina/hdw_bug/lib/python3.6/site-packages/pydarn/utils/

I can add in the message hardware files are found under `utils/hdw` in the pydarn folder structure. 

Where do you get them:  `for it by checking: https://github.com/vtsuperdarn/hdw.dat`

What am I looking for: `dcn radar.`

So I make the small tweak, but it comes to read the error message accurately. I can add this to a troubleshooting section of pyDARN to put it more to a higher-level of software dev terms. 

5. Reinstall for new hardware files?
Yes, this is valid, and in a new issue, I will address this and fix it for the next release on 1.2 as we don't produce new radars that quickly. 

6. setup.py only works with the install?
 Well, yea, its how I could make the hardware files install seamlessly. Hopefully, fixing 5 will make `develop` work, but this will be a time hit too. 

I think I addressed all the points. After dividing the valid issues to other locations, I will close this issue. Thank you again for pointing this out as it brought up some interesting information on pip and reinstalling for hardware files.

**Comment by mts299** [comment]
Made the above issues all linkig to this one. Since the real bug was not using pyDARN due to the missing hardware file and we figured that out and You got it fixed I am closing the issue now. 

Other comments can go to the other issues made.
